[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --baud 4000000 --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --baud 921600 --monitor"
rustflags = [
  # GNU LD
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",

  # LLD
  # "-C", "link-arg=-Tlinkall.x",
  # "-C", "linker=rust-lld",
]

[build]
target = "riscv32imc-unknown-none-elf"
rustdocflags = [
  "-Z", "unstable-options",
  "--generate-link-to-definition",
  "--document-hidden-items",
  "--document-private-items",
  "--enable-index-page",
  "--show-type-layout",
]

[env]
ESP_LOG = "TRACE"
# smoltcp panics if more DNS servers than this value are returned, the default is 1
SMOLTCP_DNS_MAX_SERVER_COUNT = "2"
NTP_SERVER = "uk.pool.ntp.org"
LATITUDE = "51.481583" # Centre of Cardiff
LONGITUDE = "-3.179090"

[unstable]
build-std = ["alloc", "core"]
