#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); cd ..; pwd )";
cd "$repo_dir"

PORT=${PORT:-/dev/ttyUSB0}

BIN=blind FEATURES=esp32,esp-alloc,esp-hal-embassy,wifi PORT=$PORT CHIP=esp32 scripts/run
